import type { Option } from '#/components/texcra-ui/relationship-multi-select/types'

/** Mock authors — enough to demonstrate multi-page pagination */
export const AUTHORS: Option[] = Array.from({ length: 35 }, (_, i) => ({
  value: `author-${i + 1}`,
  label: [
    'Demo Author',
    'Tien Nguyen',
    'Jane Smith',
    'Alex Johnson',
    'Maria Garcia',
    'Liam Brown',
    'Sophia Wilson',
    'Noah Martinez',
    'Olivia Anderson',
    'Ethan Thomas',
    'Ava Jackson',
    'Lucas White',
    'Isabella Harris',
    'Mason Clark',
    'Mia Lewis',
    'Logan Robinson',
    'Charlotte Walker',
    'James Hall',
    'Amelia Allen',
    'Benjamin Young',
    'Harper King',
    'Elijah Wright',
    'Evelyn Scott',
    'William Green',
    'Abigail Adams',
    'Henry Baker',
    'Emily Nelson',
    'Sebastian Hill',
    'Elizabeth Ramirez',
    'Jack Campbell',
    'Sofia Mitchell',
    'Daniel Roberts',
    'Avery Carter',
    'Matthew Phillips',
    'Scarlett Evans',
  ][i],
}))

/** Mock categories */
export const CATEGORIES: Option[] = Array.from({ length: 25 }, (_, i) => ({
  value: `category-${i + 1}`,
  label: [
    'News',
    'Tutorials',
    'Product Updates',
    'Engineering',
    'Design',
    'Marketing',
    'Sales',
    'Support',
    'Community',
    'Events',
    'Case Studies',
    'Interviews',
    'Opinion',
    'Research',
    'Industry',
    'Technology',
    'Business',
    'Startups',
    'AI & ML',
    'Web Development',
    'Mobile',
    'DevOps',
    'Security',
    'Open Source',
    'Career',
  ][i],
}))

/** Mock related posts */
export const RELATED_POSTS: Option[] = Array.from({ length: 41 }, (_, i) => ({
  value: `post-${i + 1}`,
  label: [
    'Dollar and sense: The financial forecast',
    'Getting started with Lexical',
    'Building Rich Text Editors',
    'Content Management Best Practices',
    'The Future of Web Development',
    'Understanding Server Components',
    'Mastering TypeScript Generics',
    'CSS Grid Layout Deep Dive',
    'React 19 New Features',
    'TanStack Router Guide',
    'Vite vs Webpack Performance',
    'Tailwind CSS v4 Migration',
    'Node.js Best Practices 2025',
    'GraphQL vs REST in 2025',
    'Micro-Frontends Architecture',
    'Web Performance Optimization',
    'Accessibility First Development',
    'Testing React Components',
    'Database Design Patterns',
    'API Security Fundamentals',
    'Progressive Web Apps Guide',
    'WebSocket Real-Time Apps',
    'Docker for Frontend Devs',
    'CI/CD Pipeline Setup',
    'Monorepo vs Polyrepo',
    'State Management Compared',
    'Animation with GSAP',
    'SEO for Single Page Apps',
    'Internationalization with Paraglide',
    'Building a CMS from Scratch',
    'Edge Computing Explained',
    'Serverless Functions Guide',
    'Design System Architecture',
    'Component Library Patterns',
    'Error Handling Strategies',
    'Caching Strategies Explained',
    'OAuth 2.0 Implementation',
    'WebAssembly for Beginners',
    'Rust for Web Developers',
    'The Art of Code Review',
    'End-to-End Type Safety',
  ][i],
}))

/** Registry mapping collection slugs to their data */
export const COLLECTIONS: Record<string, Option[] | undefined> = {
  authors: AUTHORS,
  categories: CATEGORIES,
  posts: RELATED_POSTS,
  'related-posts': RELATED_POSTS,
  'related posts': RELATED_POSTS,
}
