import type { Post } from './types'
import type { SerializedEditorState } from 'lexical'

export const POSTS: Post[] = [
  {
    id: 1,
    title: 'Getting Started with Lexical',
    slug: 'getting-started-with-lexical',
    status: 'published',
    meta_title: 'Getting Started with Lexical',
    meta_description:
      'Lexical is an extensible text editor framework that provides excellent reliability, accessibility, and performance.',
    meta_image_id: '101',
    heroImage: {
      id: 101,
      url: '/media/lexical-hero.jpg',
      alt: 'Lexical editor screenshot',
      filename: 'lexical-hero.jpg',
      mimeType: 'image/jpeg',
      width: 1200,
      height: 630,
    },
    authors: [{ id: 1, name: 'Admin', email: 'admin@example.com' }],
    categories: [{ id: 1, title: 'Tutorials', slug: 'tutorials' }],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'heading',
            tag: 'h2',
            children: [
              {
                type: 'text',
                text: 'Welcome to Lexical',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Lexical is an extensible text editor framework that provides excellent reliability, accessibility, and performance.',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'This is a dummy post to demonstrate the API response structure.',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    } as unknown as SerializedEditorState,
    publishedAt: '2024-10-14T00:00:00.000Z',
    createdAt: '2024-10-14T23:15:15.176Z',
    updatedAt: '2024-10-14T23:15:15.176Z',
  },
  {
    id: 2,
    title: 'Building Rich Text Editors',
    slug: 'building-rich-text-editors',
    status: 'published',
    meta_title: 'Building Rich Text Editors',
    meta_description:
      'Rich text editors are one of the most complex UI components to build correctly.',
    heroImage: null,
    authors: [{ id: 1, name: 'Admin', email: 'admin@example.com' }],
    categories: [{ id: 2, title: 'Engineering', slug: 'engineering' }],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'Rich text editors are one of the most complex UI components to build correctly.',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    } as unknown as SerializedEditorState,
    publishedAt: '2024-11-01T12:00:00.000Z',
    createdAt: '2024-11-01T10:30:00.000Z',
    updatedAt: '2024-11-01T12:00:00.000Z',
  },
  {
    id: 3,
    title: 'Content Management Best Practices',
    slug: 'content-management-best-practices',
    status: 'draft',
    meta_title: 'Content Management Best Practices',
    meta_description:
      'A well-structured content model makes everything easier — from authoring to rendering to migration.',
    meta_image_id: '102',
    heroImage: {
      id: 102,
      url: '/media/cms-hero.jpg',
      alt: 'CMS dashboard',
      filename: 'cms-hero.jpg',
      mimeType: 'image/jpeg',
      width: 1600,
      height: 900,
    },
    authors: [
      { id: 1, name: 'Admin', email: 'admin@example.com' },
      { id: 2, name: 'Editor', email: 'editor@example.com' },
    ],
    categories: [
      { id: 1, title: 'Tutorials', slug: 'tutorials' },
      { id: 2, title: 'Engineering', slug: 'engineering' },
    ],
    content: {
      root: {
        type: 'root',
        children: [
          {
            type: 'heading',
            tag: 'h2',
            children: [
              {
                type: 'text',
                text: 'Why Structure Matters',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
          {
            type: 'paragraph',
            children: [
              {
                type: 'text',
                text: 'A well-structured content model makes everything easier — from authoring to rendering to migration.',
                detail: 0,
                format: 0,
                mode: 'normal',
                style: '',
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
            textFormat: 0,
            textStyle: '',
          },
        ],
        direction: 'ltr',
        format: '',
        indent: 0,
        version: 1,
      },
    } as unknown as SerializedEditorState,
    publishedAt: null,
    createdAt: '2024-12-01T08:00:00.000Z',
    updatedAt: '2024-12-05T14:22:00.000Z',
  },
]
