Table "categories" {
  "id" integer [pk]
  "title" text [not null]
  "generate_slug" integer [default: true]
  "slug" text [not null]
  "parent_id" integer
  "updated_at" integer [not null, default: 0]
  "created_at" integer [not null, default: 0]

  Indexes {
    created_at [name: "categories_created_at_idx"]
    parent_id [name: "categories_parent_idx"]
    slug [unique, name: "categories_slug_idx"]
    updated_at [name: "categories_updated_at_idx"]
  }
}

Table "categories_breadcrumbs" {
  "order" integer [not null]
  "parent_id" integer [not null]
  "id" text [pk]
  "doc_id" integer
  "url" text
  "label" text

  Indexes {
    doc_id [name: "categories_breadcrumbs_doc_idx"]
    order [name: "categories_breadcrumbs_order_idx"]
    parent_id [name: "categories_breadcrumbs_parent_id_idx"]
  }
}

Table "media" {
  "id" integer [pk]
  "alt" text
  "caption" text
  "folder_id" integer
  "updated_at" integer [not null, default: 0]
  "created_at" integer [not null, default: 0]
  "url" text
  "thumbnail_u_r_l" text
  "filename" text
  "mime_type" text
  "filesize" numeric
  "width" numeric
  "height" numeric
  "focal_x" numeric
  "focal_y" numeric
  "sizes_thumbnail_url" text
  "sizes_thumbnail_width" numeric
  "sizes_thumbnail_height" numeric
  "sizes_thumbnail_mime_type" text
  "sizes_thumbnail_filesize" numeric
  "sizes_thumbnail_filename" text
  "sizes_square_url" text
  "sizes_square_width" numeric
  "sizes_square_height" numeric
  "sizes_square_mime_type" text
  "sizes_square_filesize" numeric
  "sizes_square_filename" text
  "sizes_small_url" text
  "sizes_small_width" numeric
  "sizes_small_height" numeric
  "sizes_small_mime_type" text
  "sizes_small_filesize" numeric
  "sizes_small_filename" text
  "sizes_medium_url" text
  "sizes_medium_width" numeric
  "sizes_medium_height" numeric
  "sizes_medium_mime_type" text
  "sizes_medium_filesize" numeric
  "sizes_medium_filename" text
  "sizes_large_url" text
  "sizes_large_width" numeric
  "sizes_large_height" numeric
  "sizes_large_mime_type" text
  "sizes_large_filesize" numeric
  "sizes_large_filename" text
  "sizes_xlarge_url" text
  "sizes_xlarge_width" numeric
  "sizes_xlarge_height" numeric
  "sizes_xlarge_mime_type" text
  "sizes_xlarge_filesize" numeric
  "sizes_xlarge_filename" text
  "sizes_og_url" text
  "sizes_og_width" numeric
  "sizes_og_height" numeric
  "sizes_og_mime_type" text
  "sizes_og_filesize" numeric
  "sizes_og_filename" text

  Indexes {
    created_at [name: "media_created_at_idx"]
    filename [unique, name: "media_filename_idx"]
    folder_id [name: "media_folder_idx"]
    sizes_large_filename [name: "media_sizes_large_sizes_large_filename_idx"]
    sizes_medium_filename [name: "media_sizes_medium_sizes_medium_filename_idx"]
    sizes_og_filename [name: "media_sizes_og_sizes_og_filename_idx"]
    sizes_small_filename [name: "media_sizes_small_sizes_small_filename_idx"]
    sizes_square_filename [name: "media_sizes_square_sizes_square_filename_idx"]
    sizes_thumbnail_filename [name: "media_sizes_thumbnail_sizes_thumbnail_filename_idx"]
    sizes_xlarge_filename [name: "media_sizes_xlarge_sizes_xlarge_filename_idx"]
    updated_at [name: "media_updated_at_idx"]
  }
}

Table "payload_folders" {
  "id" integer [pk]
  "name" text [not null]
  "folder_id" integer
  "updated_at" integer [not null, default: 0]
  "created_at" integer [not null, default: 0]

  Indexes {
    created_at [name: "payload_folders_created_at_idx"]
    folder_id [name: "payload_folders_folder_idx"]
    name [name: "payload_folders_name_idx"]
    updated_at [name: "payload_folders_updated_at_idx"]
  }
}

Table "payload_folders_folder_type" {
  "order" integer [not null]
  "parent_id" integer [not null]
  "value" text
  "id" integer [pk]

  Indexes {
    order [name: "payload_folders_folder_type_order_idx"]
    parent_id [name: "payload_folders_folder_type_parent_idx"]
  }
}

Table "posts" {
  "id" integer [pk]
  "title" text
  "hero_image_id" integer
  "content" text
  "meta_title" text
  "meta_image_id" integer
  "meta_description" text
  "published_at" integer
  "generate_slug" integer [default: true]
  "slug" text
  "updated_at" integer [not null, default: 0]
  "created_at" integer [not null, default: 0]
  "status" text [default: 'draft']

  Indexes {
    status [name: "posts__status_idx"]
    created_at [name: "posts_created_at_idx"]
    hero_image_id [name: "posts_hero_image_idx"]
    meta_image_id [name: "posts_meta_meta_image_idx"]
    slug [unique, name: "posts_slug_idx"]
    updated_at [name: "posts_updated_at_idx"]
  }
}

Table "posts_categories" {
  "parent_id" integer [not null]
  "category_id" integer [not null]
  "order" integer

  Indexes {
    (parent_id, category_id) [pk, name: "posts_categories_pk"]
    order [name: "posts_categories_order_idx"]
    parent_id [name: "posts_categories_parent_id_idx"]
    category_id [name: "posts_categories_category_id_idx"]
  }
}

Table "posts_populated_authors" {
  "order" integer [not null]
  "parent_id" integer [not null]
  "id" text [pk]
  "name" text

  Indexes {
    order [name: "posts_populated_authors_order_idx"]
    parent_id [name: "posts_populated_authors_parent_id_idx"]
  }
}

Table "posts_related_posts" {
  "parent_id" integer [not null]
  "related_post_id" integer [not null]
  "order" integer

  Indexes {
    (parent_id, related_post_id) [pk, name: "posts_related_posts_pk"]
    order [name: "posts_related_posts_order_idx"]
    parent_id [name: "posts_related_posts_parent_id_idx"]
    related_post_id [name: "posts_related_posts_related_post_id_idx"]
  }
}

Table "posts_users" {
  "parent_id" integer [not null]
  "user_id" integer [not null]
  "order" integer

  Indexes {
    (parent_id, user_id) [pk, name: "posts_users_pk"]
    order [name: "posts_users_order_idx"]
    parent_id [name: "posts_users_parent_id_idx"]
    user_id [name: "posts_users_user_id_idx"]
  }
}

Table "_posts_v" {
  "id" integer [pk]
  "parent_id" integer
  "version_title" text
  "version_hero_image_id" integer
  "version_content" text
  "version_meta_title" text
  "version_meta_image_id" integer
  "version_meta_description" text
  "version_published_at" integer
  "version_generate_slug" integer [default: true]
  "version_slug" text
  "version_updated_at" integer
  "version_created_at" integer
  "version_status" text [default: 'draft']
  "created_at" integer [not null, default: 0]
  "updated_at" integer [not null, default: 0]
  "latest" integer
  "autosave" integer

  Indexes {
    autosave [name: "_posts_v_autosave_idx"]
    created_at [name: "_posts_v_created_at_idx"]
    latest [name: "_posts_v_latest_idx"]
    parent_id [name: "_posts_v_parent_idx"]
    updated_at [name: "_posts_v_updated_at_idx"]
    version_meta_image_id [name: "_posts_v_version_meta_version_meta_image_idx"]
    version_status [name: "_posts_v_version_version__status_idx"]
    version_created_at [name: "_posts_v_version_version_created_at_idx"]
    version_hero_image_id [name: "_posts_v_version_version_hero_image_idx"]
    version_slug [name: "_posts_v_version_version_slug_idx"]
    version_updated_at [name: "_posts_v_version_version_updated_at_idx"]
  }
}

Table "_posts_v_categories" {
  "parent_id" integer [not null]
  "category_id" integer [not null]
  "order" integer

  Indexes {
    (parent_id, category_id) [pk, name: "_posts_v_categories_pk"]
    order [name: "_posts_v_categories_order_idx"]
    parent_id [name: "_posts_v_categories_version_id_idx"]
    category_id [name: "_posts_v_categories_category_id_idx"]
  }
}

Table "_posts_v_related_posts" {
  "parent_id" integer [not null]
  "related_post_id" integer [not null]
  "order" integer

  Indexes {
    (parent_id, related_post_id) [pk, name: "_posts_v_related_posts_pk"]
    order [name: "_posts_v_related_posts_order_idx"]
    parent_id [name: "_posts_v_related_posts_version_id_idx"]
    related_post_id [name: "_posts_v_related_posts_related_post_id_idx"]
  }
}

Table "_posts_v_users" {
  "parent_id" integer [not null]
  "user_id" integer [not null]
  "order" integer

  Indexes {
    (parent_id, user_id) [pk, name: "_posts_v_users_pk"]
    order [name: "_posts_v_users_order_idx"]
    parent_id [name: "_posts_v_users_version_id_idx"]
    user_id [name: "_posts_v_users_user_id_idx"]
  }
}

Table "_posts_v_version_populated_authors" {
  "order" integer [not null]
  "parent_id" integer [not null]
  "id" integer [pk]
  "uuid" text
  "name" text

  Indexes {
    order [name: "_posts_v_version_populated_authors_order_idx"]
    parent_id [name: "_posts_v_version_populated_authors_parent_id_idx"]
  }
}

Table "search" {
  "id" integer [pk]
  "title" text
  "priority" numeric
  "slug" text
  "meta_title" text
  "meta_description" text
  "meta_image_id" integer
  "updated_at" integer [not null, default: 0]
  "created_at" integer [not null, default: 0]

  Indexes {
    created_at [name: "search_created_at_idx"]
    meta_image_id [name: "search_meta_meta_image_idx"]
    slug [name: "search_slug_idx"]
    updated_at [name: "search_updated_at_idx"]
  }
}

Table "search_categories" {
  "order" integer [not null]
  "parent_id" integer [not null]
  "id" text [pk]
  "relation_to" text
  "category_i_d" text
  "title" text

  Indexes {
    order [name: "search_categories_order_idx"]
    parent_id [name: "search_categories_parent_id_idx"]
  }
}

Table "search_posts" {
  "search_id" integer [not null]
  "post_id" integer [not null]
  "order" integer

  Indexes {
    (search_id, post_id) [pk, name: "search_posts_pk"]
    order [name: "search_posts_order_idx"]
    search_id [name: "search_posts_search_id_idx"]
    post_id [name: "search_posts_post_id_idx"]
  }
}

Table "users" {
  "id" integer [pk]
  "name" text
  "updated_at" integer [not null, default: 0]
  "created_at" integer [not null, default: 0]
  "email" text [not null]
  "reset_password_token" text
  "reset_password_expiration" integer
  "salt" text
  "hash" text
  "login_attempts" numeric [default: '0']
  "lock_until" integer

  Indexes {
    created_at [name: "users_created_at_idx"]
    email [unique, name: "users_email_idx"]
    updated_at [name: "users_updated_at_idx"]
  }
}

Table "users_sessions" {
  "order" integer [not null]
  "parent_id" integer [not null]
  "id" text [pk]
  "created_at" integer
  "expires_at" integer [not null]

  Indexes {
    order [name: "users_sessions_order_idx"]
    parent_id [name: "users_sessions_parent_id_idx"]
  }
}

Ref "fk_categories_parent_id_categories_id_fk":"categories"."id" ?<? "categories"."parent_id" [delete: set null]

Ref "fk_categories_breadcrumbs_parent_id_categories_id_fk":"categories"."id" <? "categories_breadcrumbs"."parent_id" [delete: cascade]

Ref "fk_categories_breadcrumbs_doc_id_categories_id_fk":"categories"."id" ?<? "categories_breadcrumbs"."doc_id" [delete: set null]

Ref "fk_media_folder_id_payload_folders_id_fk":"payload_folders"."id" ?<? "media"."folder_id" [delete: set null]

Ref "fk_payload_folders_folder_id_payload_folders_id_fk":"payload_folders"."id" ?<? "payload_folders"."folder_id" [delete: set null]

Ref "fk_payload_folders_folder_type_parent_id_payload_folders_id_fk":"payload_folders"."id" <? "payload_folders_folder_type"."parent_id" [delete: cascade]

Ref "fk_posts_hero_image_id_media_id_fk":"media"."id" ?<? "posts"."hero_image_id" [delete: set null]

Ref "fk_posts_meta_image_id_media_id_fk":"media"."id" ?<? "posts"."meta_image_id" [delete: set null]

Ref "fk_posts_categories_parent_id_posts_id_fk":"posts"."id" <? "posts_categories"."parent_id" [delete: cascade]

Ref "fk_posts_categories_category_id_categories_id_fk":"categories"."id" <? "posts_categories"."category_id" [delete: cascade]

Ref "fk_posts_populated_authors_parent_id_posts_id_fk":"posts"."id" <? "posts_populated_authors"."parent_id" [delete: cascade]

Ref "fk_posts_related_posts_parent_id_posts_id_fk":"posts"."id" <? "posts_related_posts"."parent_id" [delete: cascade]

Ref "fk_posts_related_posts_related_post_id_posts_id_fk":"posts"."id" <? "posts_related_posts"."related_post_id" [delete: cascade]

Ref "fk_posts_users_parent_id_posts_id_fk":"posts"."id" <? "posts_users"."parent_id" [delete: cascade]

Ref "fk_posts_users_user_id_users_id_fk":"users"."id" <? "posts_users"."user_id" [delete: cascade]

Ref "fk__posts_v_parent_id_posts_id_fk":"posts"."id" ?<? "_posts_v"."parent_id" [delete: set null]

Ref "fk__posts_v_version_hero_image_id_media_id_fk":"media"."id" ?<? "_posts_v"."version_hero_image_id" [delete: set null]

Ref "fk__posts_v_version_meta_image_id_media_id_fk":"media"."id" ?<? "_posts_v"."version_meta_image_id" [delete: set null]

Ref "fk__posts_v_categories_parent_id__posts_v_id_fk":"_posts_v"."id" <? "_posts_v_categories"."parent_id" [delete: cascade]

Ref "fk__posts_v_categories_category_id_categories_id_fk":"categories"."id" <? "_posts_v_categories"."category_id" [delete: cascade]

Ref "fk__posts_v_related_posts_parent_id__posts_v_id_fk":"_posts_v"."id" <? "_posts_v_related_posts"."parent_id" [delete: cascade]

Ref "fk__posts_v_related_posts_related_post_id_posts_id_fk":"posts"."id" <? "_posts_v_related_posts"."related_post_id" [delete: cascade]

Ref "fk__posts_v_users_parent_id__posts_v_id_fk":"_posts_v"."id" <? "_posts_v_users"."parent_id" [delete: cascade]

Ref "fk__posts_v_users_user_id_users_id_fk":"users"."id" <? "_posts_v_users"."user_id" [delete: cascade]

Ref "fk__posts_v_version_populated_authors_parent_id__posts_v_id_fk":"_posts_v"."id" <? "_posts_v_version_populated_authors"."parent_id" [delete: cascade]

Ref "fk_search_meta_image_id_media_id_fk":"media"."id" ?<? "search"."meta_image_id" [delete: set null]

Ref "fk_search_categories_parent_id_search_id_fk":"search"."id" <? "search_categories"."parent_id" [delete: cascade]

Ref "fk_search_posts_search_id_search_id_fk":"search"."id" <? "search_posts"."search_id" [delete: cascade]

Ref "fk_search_posts_post_id_posts_id_fk":"posts"."id" <? "search_posts"."post_id" [delete: cascade]

Ref "fk_users_sessions_parent_id_users_id_fk":"users"."id" <? "users_sessions"."parent_id" [delete: cascade]
