import { Input } from '#/components/ui/input'
import { Label } from '#/components/ui/label'
import { Textarea } from '#/components/ui/textarea'
import { ImageUpload } from '#/components/image-upload'
import type {
  SEO,
  DocumentSnapshot,
} from '../../../../../../lexical/core/-editor-data'
import { isWebUrl, slugify } from '../../../../../../lexical/core/-editor-data'

export function SeoPanel({
  seo,
  title,
  heroImage,
  onChange,
  snapshot,
}: {
  seo: SEO
  title: string
  heroImage?: string | null
  onChange: (seo: Partial<SEO>) => void
  snapshot: DocumentSnapshot | null
}) {
  const titleLen = seo.title.trim().length
  const titlePass = titleLen >= 50 && titleLen <= 60

  const descLen = seo.description.trim().length
  const descPass = descLen >= 100 && descLen <= 150

  const imagePass = Boolean(seo.image)

  const passedCount =
    (titlePass ? 1 : 0) + (descPass ? 1 : 0) + (imagePass ? 1 : 0)

  const handleAutoGenerateTitle = () => {
    const candidate =
      title.trim() || snapshot?.headings[0]?.text?.trim() || 'Untitled document'
    onChange({ ...seo, title: candidate })
  }

  const handleAutoGenerateDescription = () => {
    if (snapshot?.text) {
      const cleanText = snapshot.text.replace(/\s+/g, ' ').trim()
      const truncated =
        cleanText.length > 145
          ? `${cleanText.slice(0, 142).trim()}...`
          : cleanText
      onChange({ ...seo, description: truncated })
    }
  }

  const canonicalValid =
    !seo.canonicalUrl.trim() || isWebUrl(seo.canonicalUrl.trim())
  const previewUrl =
    seo.canonicalUrl.trim() && canonicalValid
      ? seo.canonicalUrl.trim()
      : `http://localhost:3000/${slugify(title)}`

  const effectiveTitle = seo.title.trim() || title.trim() || 'Untitled document'
  const effectiveDescription =
    seo.description.trim() ||
    'Add a search description to give readers a reason to click.'

  return (
    <aside
      aria-label="SEO settings"
      className="min-w-0 max-w-[760px] space-y-7 pb-6"
    >
      {/* Overall checks count banner */}
      <div className="text-[13px] font-medium text-foreground">
        {passedCount}/3 checks are passing
      </div>

      {/* Meta Title Field */}
      <div className="space-y-1.5">
        <div className="flex items-center gap-1.5 text-sm font-medium">
          <Label htmlFor="field-meta__title" className="text-sm font-medium">
            Title
          </Label>
          <span className="text-muted-foreground select-none">
            &nbsp;—&nbsp;
          </span>
          <button
            type="button"
            onClick={handleAutoGenerateTitle}
            className="text-xs text-muted-foreground hover:text-foreground underline cursor-pointer bg-transparent border-none p-0 transition-colors"
          >
            Auto-generate
          </button>
        </div>
        <p className="text-xs text-muted-foreground">
          This should be between 50 and 60 characters. For help in writing
          quality meta titles, see{' '}
          <a
            href="https://developers.google.com/search/docs/advanced/appearance/title-link#page-titles"
            target="_blank"
            rel="noopener noreferrer"
            className="underline hover:text-foreground"
          >
            best practices
          </a>
          .
        </p>
        <Input
          id="field-meta__title"
          placeholder={title || 'Enter meta title...'}
          value={seo.title}
          onChange={(event) => onChange({ ...seo, title: event.target.value })}
          className="mt-2"
        />

        {/* Title Metric Indicator */}
        <div className="flex items-center w-full gap-2.5 pt-1">
          <div
            className={`text-white text-[11px] font-medium px-1.5 py-0.5 rounded-[2px] shrink-0 leading-tight select-none ${
              titlePass
                ? 'bg-emerald-600 dark:bg-emerald-500'
                : 'bg-destructive'
            }`}
          >
            <small className="text-[11px]">
              {titlePass ? 'Good' : titleLen > 60 ? 'Too long' : 'Too short'}
            </small>
          </div>
          <div className="shrink-0 text-xs text-muted-foreground select-none">
            <small className="text-xs">
              {titleLen < 50
                ? `${titleLen}/50-60 chars, ${50 - titleLen} to go`
                : titleLen <= 60
                  ? `${titleLen}/50-60 chars, ${60 - titleLen} left over`
                  : `${titleLen}/50-60 chars, ${titleLen - 60} too many`}
            </small>
          </div>
          <div className="relative h-[2px] w-full bg-muted overflow-hidden">
            <div
              className={`h-full transition-all duration-200 ${
                titlePass
                  ? 'bg-emerald-600 dark:bg-emerald-500'
                  : 'bg-destructive'
              }`}
              style={{
                width: `${
                  titleLen < 50
                    ? Math.round((titleLen / 50) * 100)
                    : titleLen <= 60
                      ? Math.round(((titleLen - 50) / 10) * 40 + 60)
                      : 100
                }%`,
              }}
            />
          </div>
        </div>
      </div>

      {/* Meta Image Field */}
      <div className="space-y-1.5">
        <div className="flex items-center justify-between text-sm font-medium">
          <div className="flex items-center gap-1.5">
            <Label className="text-sm font-medium">Meta Image</Label>
            {heroImage && !seo.image && (
              <>
                <span className="text-muted-foreground select-none">
                  &nbsp;—&nbsp;
                </span>
                <button
                  type="button"
                  onClick={() => onChange({ ...seo, image: heroImage })}
                  className="text-xs text-muted-foreground hover:text-foreground underline cursor-pointer bg-transparent border-none p-0 transition-colors"
                >
                  Use hero image
                </button>
              </>
            )}
          </div>
        </div>

        <ImageUpload
          label=""
          value={seo.image}
          onChange={(url) => onChange({ ...seo, image: url })}
        />

        {/* Image Metric Indicator */}
        <div className="flex items-center w-full gap-2.5">
          <div
            className={`text-white text-[11px] font-medium px-1.5 py-0.5 rounded-[2px] shrink-0 leading-tight select-none ${
              imagePass
                ? 'bg-emerald-600 dark:bg-emerald-500'
                : 'bg-destructive'
            }`}
          >
            <small className="text-[11px]">
              {imagePass ? 'Good' : 'No image'}
            </small>
          </div>
        </div>
      </div>

      {/* Description Field */}
      <div className="space-y-1.5">
        <div className="flex items-center gap-1.5 text-sm font-medium">
          <Label
            htmlFor="field-meta__description"
            className="text-sm font-medium"
          >
            Description
          </Label>
          <span className="text-muted-foreground select-none">
            &nbsp;—&nbsp;
          </span>
          <button
            type="button"
            onClick={handleAutoGenerateDescription}
            className="text-xs text-muted-foreground hover:text-foreground underline cursor-pointer bg-transparent border-none p-0 transition-colors"
          >
            Auto-generate
          </button>
        </div>
        <p className="text-xs text-muted-foreground">
          This should be between 100 and 150 characters. For help in writing
          quality meta descriptions, see{' '}
          <a
            href="https://developers.google.com/search/docs/advanced/appearance/snippet#meta-descriptions"
            target="_blank"
            rel="noopener noreferrer"
            className="underline hover:text-foreground"
          >
            best practices
          </a>
          .
        </p>
        <Textarea
          id="field-meta__description"
          rows={4}
          value={seo.description}
          onChange={(event) =>
            onChange({ ...seo, description: event.target.value })
          }
          className="mt-2"
        />

        {/* Description Metric Indicator */}
        <div className="flex items-center w-full gap-2.5 pt-1">
          <div
            className={`text-white text-[11px] font-medium px-1.5 py-0.5 rounded-[2px] shrink-0 leading-tight select-none ${
              descPass ? 'bg-emerald-600 dark:bg-emerald-500' : 'bg-destructive'
            }`}
          >
            <small className="text-[11px]">
              {descPass ? 'Good' : descLen > 150 ? 'Too long' : 'Too short'}
            </small>
          </div>
          <div className="shrink-0 text-xs text-muted-foreground select-none">
            <small className="text-xs">
              {descLen < 100
                ? `${descLen}/100-150 chars, ${100 - descLen} to go`
                : descLen <= 150
                  ? `${descLen}/100-150 chars, ${150 - descLen} left over`
                  : `${descLen}/100-150 chars, ${descLen - 150} too many`}
            </small>
          </div>
          <div className="relative h-[2px] w-full bg-muted overflow-hidden">
            <div
              className={`h-full transition-all duration-200 ${
                descPass
                  ? 'bg-emerald-600 dark:bg-emerald-500'
                  : 'bg-destructive'
              }`}
              style={{
                width: `${
                  descLen < 100
                    ? Math.round((descLen / 100) * 100)
                    : descLen <= 150
                      ? Math.round(((descLen - 100) / 50) * 50 + 50)
                      : 100
                }%`,
              }}
            />
          </div>
        </div>
      </div>

      {/* Canonical URL Field */}
      <div className="space-y-1.5">
        <Label htmlFor="field-meta__canonical" className="text-sm font-medium">
          Canonical URL{' '}
          <span className="font-normal text-muted-foreground">(optional)</span>
        </Label>
        <Input
          id="field-meta__canonical"
          type="url"
          placeholder="https://yoursite.com/your-story"
          value={seo.canonicalUrl}
          aria-invalid={!canonicalValid}
          onChange={(event) =>
            onChange({ ...seo, canonicalUrl: event.target.value })
          }
          className="mt-2"
        />
        <p
          className={`text-xs ${
            canonicalValid ? 'text-muted-foreground' : 'text-destructive'
          }`}
        >
          {canonicalValid
            ? 'The final public URL, included in your HTML export.'
            : 'Enter a complete http:// or https:// URL.'}
        </p>
      </div>

      {/* Preview Section */}
      <div className="pt-2">
        <div className="text-[13px] font-medium mb-1">Preview</div>
        <div className="text-xs text-muted-foreground mb-3">
          Exact result listings may vary based on content and search relevancy.
        </div>
        <div className="rounded-[5px] border border-border bg-card/60 p-5 max-w-[600px] shadow-sm pointer-events-none space-y-1">
          <div className="text-xs text-muted-foreground truncate">
            {previewUrl}
          </div>
          <h4 className="text-[17px] font-normal text-blue-600 dark:text-blue-400 leading-snug truncate">
            {effectiveTitle}
          </h4>
          <p className="text-xs text-muted-foreground line-clamp-2 leading-relaxed">
            {effectiveDescription}
          </p>
        </div>
      </div>
    </aside>
  )
}
